spring:
  profiles:
    active: dev
  docker:
    compose:
      enabled: false
  mail:
    host: smtp.qq.com
    port: 587
    username: 1962008499@qq.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


register:
  code:
    expire: 300 # 验证码有效期 300s
    cool: 60    # 同一邮箱发送冷却 60s（防刷）


server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
